debug: empty.c ../ski-barriers.c ../ski-hyper.c ../ski-test.c
	gcc -o empty empty.c ../ski-params.c ../ski-barriers.c ../ski-hyper.c ../ski-test.c -T empty.ld -lrt  -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -g -m32 -static


